version: '3.9'

services:
  node_app:
    container_name: node_app
    build: .
    image: ktorresno/node_video_creators
    ports:
      - '8000:8000'
    env_file:
      - docker.env
    depends_on:
      - node_db

  node_db:
    container_name: node_db
    image: postgres:12
    volumes:
      - node_db_data:/var/lib/postgresql/data
    env_file:
      - docker.env

volumes:
  node_db_data: {}